# Generated by Django 4.2 on 2025-11-04 07:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='شناسه یونیک تسک', unique=True)),
                ('text', models.TextField(help_text='متنی که کاربر می\u200cخواد روی تیشرت چاپ بشه')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PROCESSING', 'در حال پردازش'), ('SUCCESS', 'موفق'), ('FAILURE', 'خطا')], default='PENDING', help_text='وضعیت فعلی تسک', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='زمان آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تسک موکاپ',
                'verbose_name_plural': 'تسک\u200cهای موکاپ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_color', models.CharField(choices=[('black', 'مشکی'), ('white', 'سفید'), ('blue', 'آبی'), ('yellow', 'زرد')], help_text='رنگ تیشرت', max_length=20)),
                ('image', models.ImageField(help_text='فایل تصویر تولید شده', upload_to='mockups/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='زمان تولید')),
                ('task', models.ForeignKey(help_text='تسک مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mockups.mockuptask')),
            ],
            options={
                'verbose_name': 'تصویر موکاپ',
                'verbose_name_plural': 'تصاویر موکاپ',
                'ordering': ['shirt_color'],
            },
        ),
    ]
